# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tvRemote.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Television(object):

    MIN_VOLUME = 0
    MAX_VOLUME = 2
    MIN_CHANNEL = 0
    MAX_CHANNEL = 3

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.powerSwitch = QtWidgets.QPushButton(self.centralwidget)
        self.powerSwitch.setGeometry(QtCore.QRect(10, 490, 181, 51))
        self.powerSwitch.setObjectName("powerSwitch")
        self.volumeUp = QtWidgets.QPushButton(self.centralwidget)
        self.volumeUp.setGeometry(QtCore.QRect(200, 490, 131, 41))
        self.volumeUp.setObjectName("volumeUp")
        self.volumeLabel = QtWidgets.QLabel(self.centralwidget)
        self.volumeLabel.setGeometry(QtCore.QRect(200, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.volumeLabel.setFont(font)
        self.volumeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.volumeLabel.setObjectName("volumeLabel")
        self.volumeDown = QtWidgets.QPushButton(self.centralwidget)
        self.volumeDown.setGeometry(QtCore.QRect(200, 570, 131, 41))
        self.volumeDown.setObjectName("volumeDown")
        self.muteButton = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(10, 560, 181, 51))
        self.muteButton.setObjectName("muteButton")
        self.channelUp = QtWidgets.QPushButton(self.centralwidget)
        self.channelUp.setGeometry(QtCore.QRect(340, 490, 131, 41))
        self.channelUp.setObjectName("channelUp")
        self.channelDown = QtWidgets.QPushButton(self.centralwidget)
        self.channelDown.setGeometry(QtCore.QRect(340, 570, 131, 41))
        self.channelDown.setObjectName("channelDown")
        self.channelLabel = QtWidgets.QLabel(self.centralwidget)
        self.channelLabel.setGeometry(QtCore.QRect(340, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.channelLabel.setFont(font)
        self.channelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.channelLabel.setObjectName("channelLabel")
        self.displayBox = QtWidgets.QLabel(self.centralwidget)
        self.displayBox.setGeometry(QtCore.QRect(10, 60, 401, 281))
        self.displayBox.setText("")
        self.displayBox.setPixmap(QtGui.QPixmap("img/off.jpg"))
        self.displayBox.setScaledContents(True)
        self.displayBox.setObjectName("displayBox")
        self.volumeBar = QtWidgets.QSlider(self.centralwidget)
        self.volumeBar.setEnabled(False)
        self.volumeBar.setGeometry(QtCore.QRect(450, 59, 22, 281))
        self.volumeBar.setMaximum(2)
        self.volumeBar.setOrientation(QtCore.Qt.Vertical)
        self.volumeBar.setObjectName("volumeBar")
        self.volumeCurrent = QtWidgets.QLabel(self.centralwidget)
        self.volumeCurrent.setGeometry(QtCore.QRect(410, 162, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(50)
        self.volumeCurrent.setFont(font)
        self.volumeCurrent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.volumeCurrent.setObjectName("volumeCurrent")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.powerSwitch.clicked.connect(self.power)
        self.channelUp.clicked.connect(self.channel_up)
        self.channelDown.clicked.connect(self.channel_down)
        self.volumeUp.clicked.connect(self.volume_up)
        self.volumeDown.clicked.connect(self.volume_down)
        self.muteButton.clicked.connect(self.mute)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.powerSwitch.setText(_translate("MainWindow", "Power"))
        self.volumeUp.setText(_translate("MainWindow", "+"))
        self.volumeLabel.setText(_translate("MainWindow", "Volume"))
        self.volumeDown.setText(_translate("MainWindow", "-"))
        self.muteButton.setText(_translate("MainWindow", "Mute"))
        self.channelUp.setText(_translate("MainWindow", "+"))
        self.channelDown.setText(_translate("MainWindow", "-"))
        self.channelLabel.setText(_translate("MainWindow", "Channel"))
        self.volumeCurrent.setText(_translate("MainWindow", "0"))


    def __init__(self):
        self.__status = False
        self.__muted = False
        self.__volume = Television.MIN_VOLUME
        self.__channel = Television.MIN_CHANNEL

    def power(self):
        if self.__status:
            self.__status = False
            self.show_off()
        else:
            self.__status = True
            if self.__channel == 0:
                self.show_channel0()
            elif self.__channel == 1:
                self.show_channel1()
            elif self.__channel == 2:
                self.show_channel2()
            elif self.__channel == 3:
                self.show_channel3()

    def mute(self):
        if self.__status:
            if self.__muted:
                self.__muted = False
                self.volumeBar.setProperty("value", self.__volume)
                self.volumeCurrent.setText(QtCore.QCoreApplication.translate("MainWindow", f"{self.__volume}"))
            else:
                self.__muted = True
                self.volumeBar.setProperty("value", 0)
                self.volumeCurrent.setText(QtCore.QCoreApplication.translate("MainWindow", "Muted"))

    def channel_up(self):
        if self.__status:
            if self.__channel == Television.MAX_CHANNEL:
                self.__channel = Television.MIN_CHANNEL
            else:
                self.__channel += 1
            if self.__channel == 0:
                self.show_channel0()
            elif self.__channel == 1:
                self.show_channel1()
            elif self.__channel == 2:
                self.show_channel2()
            elif self.__channel == 3:
                self.show_channel3()
        else:
            pass

    def channel_down(self):
        if self.__status:
            if self.__channel == Television.MIN_CHANNEL:
                self.__channel = Television.MAX_CHANNEL
            else:
                self.__channel -= 1
            if self.__channel == 0:
                self.show_channel0()
            elif self.__channel == 1:
                self.show_channel1()
            elif self.__channel == 2:
                self.show_channel2()
            elif self.__channel == 3:
                self.show_channel3()
        else:
            pass

    def volume_up(self):
        if self.__status:
            if not self.__muted:
                if self.__volume == Television.MAX_VOLUME:
                    pass
                else:
                    self.__volume += 1
                self.volumeBar.setProperty("value", self.__volume)
                self.volumeCurrent.setText(QtCore.QCoreApplication.translate("MainWindow", f"{self.__volume}"))
            else:
                pass
        else:
            pass

    def volume_down(self):
        if self.__status:
            if not self.__muted:
                if self.__volume == Television.MIN_VOLUME:
                    pass
                else:
                    self.__volume -= 1
                self.volumeBar.setProperty("value", self.__volume)
                self.volumeCurrent.setText(QtCore.QCoreApplication.translate("MainWindow", f"{self.__volume}"))
            else:
                pass
        else:
            pass

    def show_off(self):
        self.displayBox.setPixmap(QtGui.QPixmap("img/off.jpg"))

    def show_channel0(self):
        self.displayBox.setPixmap(QtGui.QPixmap("img/channel0.jpg"))

    def show_channel1(self):
        self.displayBox.setPixmap(QtGui.QPixmap("img/channel1.jpg"))

    def show_channel2(self):
        self.displayBox.setPixmap(QtGui.QPixmap("img/channel2.png"))

    def show_channel3(self):
        self.displayBox.setPixmap(QtGui.QPixmap("img/channel3.png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Television()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
