# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tvRemote.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.powerSwitch = QtWidgets.QPushButton(self.centralwidget)
        self.powerSwitch.setGeometry(QtCore.QRect(10, 490, 181, 51))
        self.powerSwitch.setObjectName("powerSwitch")
        self.volumeUp = QtWidgets.QPushButton(self.centralwidget)
        self.volumeUp.setGeometry(QtCore.QRect(200, 490, 131, 41))
        self.volumeUp.setObjectName("volumeUp")
        self.volumeLabel = QtWidgets.QLabel(self.centralwidget)
        self.volumeLabel.setGeometry(QtCore.QRect(200, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.volumeLabel.setFont(font)
        self.volumeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.volumeLabel.setObjectName("volumeLabel")
        self.volumeDown = QtWidgets.QPushButton(self.centralwidget)
        self.volumeDown.setGeometry(QtCore.QRect(200, 570, 131, 41))
        self.volumeDown.setObjectName("volumeDown")
        self.muteButton = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(10, 560, 181, 51))
        self.muteButton.setObjectName("muteButton")
        self.channelUp = QtWidgets.QPushButton(self.centralwidget)
        self.channelUp.setGeometry(QtCore.QRect(340, 490, 131, 41))
        self.channelUp.setObjectName("channelUp")
        self.channelDown = QtWidgets.QPushButton(self.centralwidget)
        self.channelDown.setGeometry(QtCore.QRect(340, 570, 131, 41))
        self.channelDown.setObjectName("channelDown")
        self.channelLabel = QtWidgets.QLabel(self.centralwidget)
        self.channelLabel.setGeometry(QtCore.QRect(340, 530, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.channelLabel.setFont(font)
        self.channelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.channelLabel.setObjectName("channelLabel")
        self.displayBox = QtWidgets.QLabel(self.centralwidget)
        self.displayBox.setGeometry(QtCore.QRect(10, 60, 401, 281))
        self.displayBox.setText("")
        self.displayBox.setPixmap(QtGui.QPixmap("channel0.jpg"))
        self.displayBox.setScaledContents(True)
        self.displayBox.setObjectName("displayBox")
        self.volumeCurrent = QtWidgets.QLabel(self.centralwidget)
        self.volumeCurrent.setGeometry(QtCore.QRect(410, 160, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.volumeCurrent.setFont(font)
        self.volumeCurrent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.volumeCurrent.setObjectName("volumeCurrent")
        self.volumeBar = QtWidgets.QSlider(self.centralwidget)
        self.volumeBar.setEnabled(False)
        self.volumeBar.setGeometry(QtCore.QRect(450, 59, 22, 281))
        self.volumeBar.setMaximum(2)
        self.volumeBar.setProperty("value", 1)
        self.volumeBar.setOrientation(QtCore.Qt.Vertical)
        self.volumeBar.setObjectName("volumeBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.powerSwitch.setText(_translate("MainWindow", "Power"))
        self.volumeUp.setText(_translate("MainWindow", "+"))
        self.volumeLabel.setText(_translate("MainWindow", "Volume"))
        self.volumeDown.setText(_translate("MainWindow", "-"))
        self.muteButton.setText(_translate("MainWindow", "Mute"))
        self.channelUp.setText(_translate("MainWindow", "+"))
        self.channelDown.setText(_translate("MainWindow", "-"))
        self.channelLabel.setText(_translate("MainWindow", "Channel"))
        self.volumeCurrent.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
